### ISSUE TITLE
Details of RDS files/objects

### ISSUE THREAD

**Issue by kloot** [JinmiaoChenLab/DISCO_learning#1]
Dear DISCO Team,

First, many thanks for making this great resource available!
We would like to use the Seurat objects from some of the curated _individual_ samples (not atlas) available in the downloadable *.rds files

Could you please provide additional details about the data in the various slots of the Seurat objects, specifically:

1) Are the normalized expression values stored in the object? Seurat's default is to store these in `@assays $RNA@data@x`, however this is empty in the objects I have inspected. 
If the normalised values are not stored in the Seurat object, could we simply re-run the Normalization command (documented in slot `@commands`) to obtain the normalized values, without effects on existing clusters?

2) Does `@assays$RNA@counts` hold the cells/barcodes in the raw (unfiltered) data matrix, or only the cells retained after data QC and filtering as described in the DISCO paper. For example, the original raw data matrix in the GEO record of GSM4085513 holds 4,511 cells, while the Seurat object in GSM4085513.rds file from DISCO holds 3,606 cells.

Many thanks in advance!

**Comment by lmw123** [comment]
Hi,

Thank you for your interest in DISCO. I wanted to provide some clarifications regarding your questions:

1. To reduce the file size, we removed the normalized data of each sample by setting rna@assays $RNA@data@x = 0. Please note that when using the data, you will need to re-run normalization.
2. The barcodes for some samples may differ from the barcodes reported in the original study as we processed the data from fastq. For quality control, we performed a basic QC to remove any empty droplets.

I hope this information is helpful. Please feel free to let me know if you have any further questions. Thank you.

Best,
Mengwei

**Comment by kloot** [comment]
Dear Mengwei,

Thank you for the clarification, makes great sense!
